### PR TITLE
Make sure all Setup scripts are run as root

### PR DESCRIPTION
**Pull request by Jeroen0494**
To prevents errors, make sure all scripts are run as root. This commit puts a simple check at the beginning of each script. It also remove all sudo commands from all files.

### CODE REVIEW

**Comment by pevma** [comment]
That seems to mean that none other than `root` can set up SELKS?
You may have `selks-user` setting up SELKS (or another one of course - if they have `sudo` priv)

**Comment by Jeroen0494** [comment]
Damn, my new commit is added to this pull request. That wasn't meant to happen.
If you run the scripts with 'sudo' before them, they will be run as root. You can test this with:
sudo id

**Comment by Jeroen0494** [comment]
You can test this with: 
sudo id

**Comment by pevma** [comment]
How would that be done if a non root user double clicks the desktop icon?

**Comment by pevma** [comment]
Could you also please separate the last commit into its own pull request ? (about the interfaces)

**Comment by Jeroen0494** [comment]
> How would that be done if a non root user double clicks the desktop icon

You would have to put "pkexec" before the command. I can make a commit for it.
But it looks like SELKS doesn't have pkexec (libpolkit) included by default. You could use gksu, but it is basically deprecated.



> Could you also please separate the last commit into its own pull request ? (about the interfaces)

I reverted the commit. That's about all the git I know. Sorry.

**Comment by pevma** [comment]
I just updated the main brunch with your suggestions picked up for here. Thank you @Jeroen0494 !
Looking forward to the ``pkexec`` trick!

**Pull request closed without merging**
